# Generated by Django 4.0.3 on 2022-03-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_postimage_blogimage'),
        ('accounts', '0004_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='restaurants.restaurant'),
        ),
    ]
