# Generated by Django 4.0.3 on 2022-03-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_postimage_blogimage'),
        ('accounts', '0005_remove_user_like_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followings', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='liked_blogs', to='restaurants.blog'),
        ),
    ]
