# Generated by Django 4.0.3 on 2022-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_followers_remove_user_followings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
