# Generated by Django 4.0.3 on 2022-03-15 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0006_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Liked'), ('follow', 'Followed'), ('comment', 'Commented')], max_length=10)),
                ('Target', models.CharField(choices=[('blog', 'Blog'), ('rest', 'Restaurant')], max_length=10)),
                ('blog_id', models.IntegerField(default=-1)),
                ('restaurant_id', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('TargetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getnotification', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
