# Generated by Django 4.0.3 on 2022-04-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='blog_id',
            new_name='target_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='restaurant_id',
        ),
    ]
