# Generated by Django 4.0.3 on 2022-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0008_rename_blog_id_notification_target_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Target',
            field=models.CharField(choices=[('blog', 'Blog'), ('rest', 'Restaurant'), ('new_blog', 'New Blog'), ('menu', 'Menu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('like', 'Liked'), ('follow', 'Followed'), ('comment', 'Commented'), ('update', 'Updated'), ('make', 'made')], max_length=10),
        ),
    ]
