# Generated by Django 4.0.3 on 2022-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0011_alter_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rest_name',
            field=models.CharField(default='Not Applicable', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(default='Impossible', max_length=200),
        ),
    ]
