# Generated by Django 4.0.3 on 2022-04-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0012_notification_rest_name_notification_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='rest_name',
        ),
    ]
