# Generated by Django 4.0.3 on 2022-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_postimage_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='followed',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='follower_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Followed',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
