# Generated by Django 4.0.3 on 2022-03-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_avatar',
        ),
    ]
