# Generated by Django 4.0.3 on 2022-03-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_followers_remove_user_followings_and_more'),
        ('restaurants', '0005_remove_followed_restaurants_remove_followed_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='follower_num',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='like_num',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
