# Generated by Django 4.0.3 on 2022-03-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurant_restaurant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
