# Generated by Django 4.0.3 on 2022-03-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_blogimage_post_remove_restaurant_comment_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='follower_num',
            field=models.IntegerField(default=0),
        ),
    ]
