# Generated by Django 4.0.3 on 2022-03-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_follower_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='follower_num',
        ),
    ]
